import landingIcon from "../assets/landing.svg";
import aboutIcon from "../assets/about.svg";
import projectsIcon from "../assets/projects.svg";
import mainCover from "../assets/mainCover.png";
import js from "../assets/js.svg";
import md from "../assets/md.svg";
import git from "../assets/git.svg";
import rectangle from "../assets/rectangle.png";
import html from "../assets/html.svg";
import css from "../assets/css.svg";
import javascript from "../assets/javascript.svg";
import materialUi from "../assets/materialUi.svg";
import typeScript from "../assets/typeScript.svg";
import react from "../assets/react.svg";
import next from "../assets/next.svg";
import redux from "../assets/redux.svg";
import node from "../assets/node.svg";
import angular from "../assets/angular.svg";
import bootstrap from "../assets/bootstrap.svg";
import figma from "../assets/figma.svg";
import tailwind from "../assets/tailwind.svg";
import linux from "../assets/linux.svg";
import github from "../assets/github.svg";
import linkedin from "../assets/linkedin.svg";
import arrowUpRight from "../assets/arrow-up-right.svg";
import rectangleTwo from "../assets/rectangleTwo.png";
import cover from "../assets/cover.png";
import coverOne from "../assets/coverOne.png";
import coverTwo from "../assets/coverTwo.png";
import coverThree from "../assets/cover-Three.png";
import coverFour from "../assets/coverFour.png";
import experienceIcon from "../assets/experienceIcon.svg";
import star from "../assets/star.svg";


// Define types for icons
type IconType = string;

export const IlandingIcon: IconType = landingIcon;
export const IaboutIcon: IconType = aboutIcon;
export const IprojectsIcon: IconType = projectsIcon;
export const ImainCover: IconType = mainCover;
export const Ijs: IconType = js;
export const Imd: IconType = md;
export const Igit: IconType = git;
export const Irectangle: IconType = rectangle;
export const Ihtml: IconType = html;
export const Icss: IconType = css;
export const Ijavascript: IconType = javascript;
export const ImaterialUi: IconType = materialUi;
export const ItypeScript: IconType = typeScript;
export const Ireact: IconType = react;
export const Inext: IconType = next;
export const Iredux: IconType = redux;
export const Inode: IconType = node;
export const Iangular: IconType = angular;
export const Ibootstrap: IconType = bootstrap;
export const Ifigma: IconType = figma;
export const Itailwind: IconType = tailwind;
export const Ilinux: IconType = linux;
export const Igithub: IconType = github;
export const Ilinkedin: IconType = linkedin;
export const IarrowUpRight: IconType = arrowUpRight;
export const IrectangleTwo: IconType = rectangleTwo;
export const Icover: IconType = cover;
export const IcoverOne: IconType = coverOne;
export const IcoverTwo: IconType = coverTwo;
export const IcoverThree: IconType = coverThree;
export const IcoverFour: IconType = coverFour;
export const IexperienceIcon: IconType = experienceIcon;
export const Istar: IconType = star;
